//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTS()
        {
            this.SALES = new HashSet<SALES>();
        }
    
        public string CLIENT_CODE { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CONTACT_PHONE { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public Nullable<System.DateTime> INSERTED_AT { get; set; }
        public string USER_CODE { get; set; }
    
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALES> SALES { get; set; }
    }
}
