//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpPOSEntities : DbContext
    {
        public OpPOSEntities()
            : base("name=OpPOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APP_MODULES> APP_MODULES { get; set; }
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<COMPANY_DATA> COMPANY_DATA { get; set; }
        public virtual DbSet<CORRELATIVES> CORRELATIVES { get; set; }
        public virtual DbSet<EMPLOYEE_USER> EMPLOYEE_USER { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<INVENTORY> INVENTORY { get; set; }
        public virtual DbSet<INVENTORY_ENTRIES> INVENTORY_ENTRIES { get; set; }
        public virtual DbSet<INVENTORY_ENTRY_DETAILS> INVENTORY_ENTRY_DETAILS { get; set; }
        public virtual DbSet<INVENTORY_EXIT_DETAILS> INVENTORY_EXIT_DETAILS { get; set; }
        public virtual DbSet<INVENTORY_EXITS> INVENTORY_EXITS { get; set; }
        public virtual DbSet<ISV_TYPES> ISV_TYPES { get; set; }
        public virtual DbSet<LOGBOOK_APP> LOGBOOK_APP { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<ROLE_PERMISSIONS> ROLE_PERMISSIONS { get; set; }
        public virtual DbSet<SALE_DETAILS> SALE_DETAILS { get; set; }
        public virtual DbSet<SALES> SALES { get; set; }
        public virtual DbSet<SUPPLIERS> SUPPLIERS { get; set; }
        public virtual DbSet<SYSTEM_LICENSE> SYSTEM_LICENSE { get; set; }
        public virtual DbSet<USER_PERMISSIONS> USER_PERMISSIONS { get; set; }
        public virtual DbSet<USER_ROLES> USER_ROLES { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
