//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEES()
        {
            this.EMPLOYEE_USER = new HashSet<EMPLOYEE_USER>();
            this.EMPLOYEE_SALARY = new HashSet<EMPLOYEE_SALARY>();
        }
    
        public string EMPLOYEE_CODE { get; set; }
        public string EMPLOYEE_DNI { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_LASTNAME { get; set; }
        public string EMPLOYEE_EMAIL { get; set; }
        public string EMPLOYEE_PHONE { get; set; }
        public string EMPLOYEE_ADDRESS { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public bool IS_DEL { get; set; }
        public string USER_CODE { get; set; }
        public string JOB_POSITION_CODE { get; set; }
        public string HORARY_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_USER> EMPLOYEE_USER { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_SALARY> EMPLOYEE_SALARY { get; set; }
    }
}
