//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_CARDEX
    {
        public int CARDEX_ID { get; set; }
        public string COD_PRODUCT { get; set; }
        public System.DateTime MOVEMENT_DATE { get; set; }
        public string MOVEMENT_TYPE { get; set; }
        public int QUANTITY { get; set; }
        public int STOCK_BEFORE { get; set; }
        public int STOCK_AFTER { get; set; }
        public string REFERENCE { get; set; }
        public string USER_CODE { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
