//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        public string COD_PRODUCT { get; set; }
        public int STOCK_MIN { get; set; }
        public int STOCK_CURRENT { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public string USER_CODE { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
