//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_ENTRIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY_ENTRIES()
        {
            this.INVENTORY_ENTRY_DETAILS = new HashSet<INVENTORY_ENTRY_DETAILS>();
        }
    
        public string ENTRY_ID { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public decimal TOTAL_AMOUNT { get; set; }
        public string USER_CODE { get; set; }
    
        public virtual SUPPLIERS SUPPLIERS { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_ENTRY_DETAILS> INVENTORY_ENTRY_DETAILS { get; set; }
    }
}
