//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_EXIT_DETAILS
    {
        public int DETAIL_ID { get; set; }
        public int EXIT_ID { get; set; }
        public string COD_PRODUCT { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual INVENTORY_EXITS INVENTORY_EXITS { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
