//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGBOOK_APP
    {
        public long LOG_ID { get; set; }
        public string LOG_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> INSERTED_AT { get; set; }
        public string USER_CODE { get; set; }
        public string MODULE_ID { get; set; }
        public string ACTION_TYPE { get; set; }
    
        public virtual APP_MODULES APP_MODULES { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
