//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.INVENTORY_CARDEX = new HashSet<INVENTORY_CARDEX>();
            this.INVENTORY_ENTRY_DETAILS = new HashSet<INVENTORY_ENTRY_DETAILS>();
            this.INVENTORY_EXIT_DETAILS = new HashSet<INVENTORY_EXIT_DETAILS>();
            this.SALE_DETAILS = new HashSet<SALE_DETAILS>();
        }
    
        public string COD_PRODUCT { get; set; }
        public string PRODUCT_NAME { get; set; }
        public decimal PRODUCT_PRICE { get; set; }
        public Nullable<System.DateTime> INSERTED_AT { get; set; }
        public string USER_CODE { get; set; }
        public int COD_ISV { get; set; }
    
        public virtual INVENTORY INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_CARDEX> INVENTORY_CARDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_ENTRY_DETAILS> INVENTORY_ENTRY_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_EXIT_DETAILS> INVENTORY_EXIT_DETAILS { get; set; }
        public virtual ISV_TYPES ISV_TYPES { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_DETAILS> SALE_DETAILS { get; set; }
    }
}
