//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALES()
        {
            this.BILL = new HashSet<BILL>();
            this.SALE_DETAILS = new HashSet<SALE_DETAILS>();
        }
    
        public string SALE_ID { get; set; }
        public string CLIENT_CODE { get; set; }
        public System.DateTime SALE_DATE { get; set; }
        public decimal TOTAL_AMOUNT { get; set; }
        public string USER_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILL { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE_DETAILS> SALE_DETAILS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
